version: '3'

services:
  teamgranitemongonodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: teamgranitemongonodejs
    restart: always
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=teamgranitemongodb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "7501:5000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh teamgranitemongodb:27017 -- /home/node/app/node_modules/.bin/nodemon app.js 

  teamgranitemongodb:
    image: mongo:4.1.8-xenial
    container_name: teamgranitemongodb
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  
